server.address=0.0.0.0
server.port=8080

spring.datasource.url=jdbc:h2:file:./data/wedding
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Email настройки
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=emengulov.artyom@yandex.rum
spring.mail.password=jpuvuzkktreszjti
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Куда отправлять уведомления
wedding.notification.email=artem.emengulov@mail.ru